### ISSUE TITLE
[Feature Request] Add support for Custom Biomes with Terra Plugin

### ISSUE THREAD

**Issue by sherry5299** [Happy-Hop7/RealisticPlantGrowth#15] opened 2024-02-12 13:47 UTC
Does the plugin support Terra ?
https://www.spigotmc.org/resources/terra.85151/

**Comment by Happy-Hop7** [comment] 2024-02-13 11:03
At the current stage of development, the plugin does not yet support custom biomes. 
However, I want to assure you that this feature is in my plans and will be implemented within the next few months. 
Please understand that I'm currently in the midst of my university exam phase, which limits the time I have available until the end of March.

**Comment by Happy-Hop7** [comment] 2024-02-13 13:25
Duplicate of #12.

**Comment by Happy-Hop7** [comment] 2024-10-31 08:27
Support for custom biomes added in 9f8bf0badf460d862b5931d3c8c5b7c682b350a5.

**Closed** 2024-11-04 22:43 UTC
Labels: enhancement
